name: test_login
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  flutter_bloc: ^8.0.1
  formz: ^0.4.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  uuid: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.0.2
  mocktail: ^0.2.0
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/google_icon.png
    - assets/images/facebook_icon.png
    - assets/images/apple_icon.png
    - assets/images/visibility_off_icon.png
    - assets/images/bird_icon.png


  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/Ubuntu-R.ttf
    - family: Ubuntu-B
      fonts:
        - asset: assets/Ubuntu-B.ttf
